config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all

		respond_to do |format|
			format.html
			format.json { render :json => @kittens }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "New Kitten created!"
			redirect_to @kitten 
			
		else 
			flash[:failure] = "Something went wrong"
			render 'new'
			
		end
 	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten updated"
			redirect_to @kitten 
				
		else
			render 'edit'
		end
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to(kittens_url)
	end


	private

		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Update Kitten</h1>

<%= form_for(@kitten) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :age %>
	<%= f.text_field :age %>

	<%= f.label :cuteness %>
	<%= f.text_field :cuteness %>

	<%= f.label :cuteness %>
	<%= f.text_field :cuteness %>

	<%= f.submit "Save Changes" %>
	
<% end %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<% @kittens.each do | kitten | %>
	<p>
		<%= link_to(kitten.name, kitten ) %> <br>
		<%= link_to("edit", edit_kitten_path(kitten)) %>
		<%= link_to("delete", kitten, method: :delete, data: { confirm: "You sure?"}) %>

	</p>
<% end %>

app/views/kittens/new.html.erb
<h1>Create a Kitten</h1>

<%= form_for(@kitten) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :age %>
	<%= f.text_field :age %>

	<%= f.label :cuteness %>
	<%= f.text_field :cuteness %>

	<%= f.label :softness %>
	<%= f.text_field :softness %>

	<%= f.submit "Create" %>

<% end %>

app/views/kittens/show.html.erb
<h1>Kitten</h1>

<h3>name: <%= @kitten.name %></h3>
<p>age: <%= @kitten.age %></p>
<p>cuteness: <%= @kitten.cuteness %></p>
<p>softness: <%= @kitten.softness %></p>
<%= link_to("edit", @kitten, method: :edit) %>

app/views/layouts/_header.html.erb
<div>
	<h3>Kittens!</h3>
	<ul>
		<li><%= link_to "index", kittens_path %></li>
		<li><%= link_to "new", new_kitten_path %></li>
	
		

	</ul>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% flash.each do |key, value| %>
        <%= value %>
      <% end %>
    </div>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @kitten.errors.any? %>
	<% @kitten.errors.full_messages.each do |message| %>
		<%= message %>
	<% end %>
<% end %>